In [151]:
import pandas as pd

In [152]:
DATA_DIR = '../data'
BASE_DATASET = f'{DATA_DIR}/base_dataset.csv'

NEAREST_LAKES = f'{DATA_DIR}/nearest_lakes.csv'
ALTITUDE = f'{DATA_DIR}/fixed_elevation_dataset.csv'
WEATHER_STATS = f'{DATA_DIR}/hpp-database-with-weather-stats.csv'

In [153]:
base_df = pd.read_csv(BASE_DATASET)
with_attributes = base_df.rename(columns={
    'id': 'plant_id'
})

In [154]:
altitude_df = pd.read_csv(ALTITUDE)[[
    'id', 
    'altitude (m)'
]]
altitude_df.rename(columns={
    'id': 'plant_id',
    'altitude (m)': 'altitude_m'
}, inplace = True)
with_attributes = with_attributes.merge(altitude_df, left_on='plant_id', right_on='plant_id')

In [155]:
lakes_df = pd.read_csv(NEAREST_LAKES)[[
    'plant_id',
    'distance_km'
]]
lakes_df.rename(columns={
    'distance_km': 'nearest_lake_dist_km'
}, inplace = True)
with_attributes = with_attributes.merge(lakes_df, left_on='plant_id', right_on='plant_id')

In [156]:
weather_df = pd.read_csv(WEATHER_STATS)[[
    'id',
    'Days of Rain',
    'Inches of Rain',
    'Avg High Temp',
    'Avg Low Temp'
]]
weather_df.rename(columns={
    'id': 'plant_id',
    'Days of Rain': 'days_of_rain',
    'Inches of Rain': 'inches_of_rain',
    'Avg High Temp': 'avg_high_temp',
    'Avg Low Temp': 'avg_low_temp'
}, inplace = True)
with_attributes = with_attributes.merge(weather_df, left_on='plant_id', right_on='plant_id')

In [158]:
with_attributes.describe()

,gwh_per_mm3,latitude,longitude,altitude_m,lake_id,nearest_lake_dist_km,days_of_rain,inches_of_rain,avg_high_temp,avg_low_temp
count,584.000000,584.000000,584.000000,584.000000,5.840000e+02,584.000000,584.000000,584.000000,584.000000,584.000000
mean,4.362764,57.413022,11.779851,398.965925,8.738502e+05,3.376309,106.243151,29.348288,52.982877,38.893836
std,12.984496,8.850098,7.890655,360.869828,5.518296e+05,3.308829,16.297274,6.312752,6.728479,5.127101
min,0.004603,37.829642,-8.500000,-1.900000,1.044000e+03,0.169887,43.000000,14.400000,47.000000,35.000000
25%,0.484287,47.067323,7.005993,122.000000,1.693432e+05,1.386615,105.000000,26.900000,49.000000,36.000000
50%,1.155219,60.227756,10.045174,312.700000,1.255992e+06,2.480934,113.000000,30.000000,49.000000,36.000000
75%,3.064718,63.034046,16.846657,606.150000,1.290632e+06,4.072938,113.000000,30.000000,58.000000,41.000000
max,207.834196,70.773472,30.706361,2774.300000,1.369046e+06,35.348131,170.000000,65.400000,72.000000,59.000000